## Where the samples will be written
save_data: models/seed-0/a50/

## Where the vocab(s) will be written
src_vocab: a50.vocab.src
tgt_vocab: a50.vocab.tgt

# Prevent overwriting existing files in the folder
overwrite: True

# Tensorboard 
tensorboard: true
tensorboard_log_dir: logs

# Corpus opts:
data:
    train:
        path_src: ../../../data/opennmt/seed-0/a50/src-train.txt
        path_tgt: ../../../data/opennmt/seed-0/a50/tgt-train.txt
    valid:
        path_src: ../../../data/opennmt/seed-0/a50/src-val.txt
        path_tgt: ../../../data/opennmt/seed-0/a50/tgt-val.txt

# Vocabulary files that were just created
src_vocab: a50.vocab.src
tgt_vocab: a50.vocab.tgt

# General opts
save_model: a50
save_checkpoint_steps: 100000
train_steps: 100000
valid_steps: 5000

# Batching
bucket_size: 262144
world_size: 1
gpu_ranks: [0]
num_workers: 4
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 2048
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
